services:
  gocron:
    image: ghcr.io/flohoss/gocron:latest
    restart: always
    container_name: gocron
    hostname: gocron
    environment:
      - TZ=Europe/Berlin
      # Uncomment and replace <token> if using ntfy notifications
      # - NTFY_URL=https://ntfy.hoss.it/
      # - NTFY_TOPIC=Backup
      # - NTFY_TOKEN=<token>
    volumes:
      - ./config/:/app/config/
      # Uncomment if using Restic with a password file
      - ./.resticpwd:/secrets/.resticpwd
      # Uncomment if using a preconfigured rclone config
      - ./.rclone.conf:/root/.config/rclone/rclone.conf
      # Uncomment to allow running Docker commands inside the container
      # - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8156:8156
