application:
  subdomain: gocron
  background_task: true
  multi_instance: false
  upstreams:
    - location: /
      backend: http://gocron.cloud.lazycat.app.gocron.lzcapp:8156/
services:
  gocron:
    # upstream: ghcr.io/flohoss/gocron:v0.11.0
    image: registry.lazycat.cloud/czyt/flohoss/gocron:efcf6448c378ec48
    environment:
      - TZ=Asia/Shanghai
    binds:
      - /lzcapp/var/config:/app/config/
      - /lzcapp/var/.resticpwd:/secrets/.resticpwd
      - /lzcapp/var/rclone.conf:/root/.config/rclone/rclone.conf
    setup_script: |
      if [ ! -f /lzcapp/var/config/config.yml ]; then
        cp /lzcapp/pkg/content/config.yml.example /lzcapp/var/config/config.yml
      fi
